/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

int main(void)
{
	uint32_t *pClkCtrlReg   = (uint32_t *)0x40023830;
	uint32_t *pPortAModeReg = (uint32_t *)0x40020000;
	uint32_t *pPortAOutReg  = (uint32_t *)0x40020014;

	/* Enable clock for GPIO A Peripheral (AHB1ENR)*/
	*pClkCtrlReg |= 0x01;

	/* Configure the mode of the IO pin as OUTPUT */
	/* a. Clear the 22th and 23th bit positions (CLEAR) */
	*pPortAModeReg &= 0xFF3FFFFF;
	/* b. make 5th bit position as 1 (SET) */
	*pPortAModeReg |= 0x0400;

	/* SET 5th bit of the output data register to make I/O pin-13 as HIGH */
	*pPortAOutReg |= 0x20;

    while(1);
}
